version: '3'

services:
  postgres:
    build:
      context: postgres
    container_name: postgres_test

  keycloak:
    image: jboss/keycloak:12.0.4
    container_name: keycloak
    environment:
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      # Already created in the dump load in postgres' image
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: Password7!
    depends_on:
      - postgres
    ports:
      - 8080:8080
